### ISSUE TITLE
Error messages in WSL Ubuntu 18.94

### ISSUE THREAD

**Issue by cfraz89** [haskell/ghcup#64]
Running ghcup in a WSL install of Ubuntu 18.04 yields the following errors/warnings:

/home/chris/.ghcup/bin/ghcup: 1: /home/chris/.ghcup/bin/ghcup: ot found
/home/chris/.ghcup/bin/ghcup: 1: /home/chris/.ghcup/bin/ghcup: 35mcurl: not found

However the script proceeeds as per usual after this anyway.

**Comment by cfraz89** [comment]
Experienced more of the same messages for each step of the install process. 

The nice thing is though, it all worked in the end :smile: 

For future reference, just needed to install these packages:

- build-essential
- zlib1g-dev
- libnuma-dev

And everything was peachy.

**Comment by hvr** [comment]
Orthogonal to the issue: on WSL you might prefer if possible to use the Ubuntu packages  specifically built and tuned for WSL at https://launchpad.net/~hvr/+archive/ubuntu/ghc-wsl unless the severe memory-allocation-related startup penalty for Haskell executables (which includes `ghc` proper) was finally fixed in WSL.
